# Generated by Django 6.0.3 on 2026-04-04 15:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Donneur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupe_sanguin', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3)),
                ('sexe', models.CharField(choices=[('M', 'Homme'), ('F', 'Femme')], max_length=1)),
                ('date_naissance', models.DateField()),
                ('ville', models.CharField(max_length=100)),
                ('actif', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Hopital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('adresse', models.TextField()),
                ('ville', models.CharField(max_length=100)),
                ('agrement', models.CharField(max_length=100, unique=True)),
                ('valide', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Don',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_don', models.DateField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('valide', models.BooleanField(default=False)),
                ('donneur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.donneur')),
                ('hopital', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='index.hopital')),
            ],
        ),
        migrations.CreateModel(
            name='DemandeUrgente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupe_sanguin', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3)),
                ('quantite', models.PositiveIntegerField(help_text='Quantité en poches')),
                ('delai', models.DateTimeField()),
                ('statut', models.CharField(choices=[('Active', 'Active'), ('Clôturée', 'Clôturée')], default='Active', max_length=20)),
                ('description', models.TextField()),
                ('hopital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.hopital')),
            ],
        ),
        migrations.CreateModel(
            name='Campagne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('lieu', models.CharField(max_length=200)),
                ('groupes_cibles', models.CharField(help_text='Ex: O-, A+, B-', max_length=100)),
                ('capacite_totale', models.PositiveIntegerField()),
                ('hopital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.hopital')),
            ],
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creneau_horaire', models.TimeField()),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('present', models.BooleanField(default=False)),
                ('campagne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.campagne')),
                ('donneur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.donneur')),
            ],
        ),
        migrations.CreateModel(
            name='ReponseAppel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_reponse', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('En attente', 'En attente'), ('Confirmée', 'Confirmée')], default='En attente', max_length=20)),
                ('demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.demandeurgente')),
                ('donneur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.donneur')),
            ],
        ),
    ]
